### PR TITLE
Switch to new python elasticsearch client for better monitoring support

### PR DESCRIPTION
**Pull request by a-marcel**
Old pyes Client not working with newer Python and newer Elasticsearch versions

### CODE REVIEW

**Comment by freeman512** [comment]
This version working ! Thx !

**Comment by freeman512** [comment]
File "/opt/zabbix/externalscripts/ESzabbix.py", line 40, in <module>
    nodestats = conn.cluster_stats()
AttributeError: 'ES' object has no attribute 'cluster_stats'
Traceback (most recent call last):
  File "/opt/zabbix/externalscripts/ESzabbix.py", line 40, in <module>
    nodestats = conn.cluster_stats()
AttributeError: 'ES' object has no attribute 'cluster_stats'
 30264:20140703:154753.565 active check "ESzabbix[cluster,initializing_shards]" is not supported
 30264:20140703:154753.642 active check "ESzabbix[cluster,relocating_shards]" is not supported
 30264:20140703:154755.720 active check "ESzabbix[cluster,status]" is not supported
 30264:20140703:154756.796 active check "ESzabbix[cluster,unassigned_shards]" is not supported
Traceback (most recent call last):
  File "/opt/zabbix/externalscripts/ESzabbix.py", line 108, in <module>
    stats = nodestats['nodes'][nodename]['indices']['cache']
KeyError: 'cache'
Traceback (most recent call last):
  File "/opt/zabbix/externalscripts/ESzabbix.py", line 108, in <module>
    stats = nodestats['nodes'][nodename]['indices']['cache']
KeyError: 'cache'

**Comment by a-marcel** [comment]
I'll check this later. Thanks.

**Comment by a-marcel** [comment]
Hi, i cannot map "field_size_in_bytes" and "filter_size_in_bytes" from "cache". What is the meaning of this values ?

@freeman512 : i cannot reproduce your errors - maybe you forgot to use my branch.

**Pull request merged**
